<a href="https://colab.research.google.com/github/earth1429/AI-ClassifyImage/blob/main/Datapapaya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing all necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# #Dome
# train_datagenerator = ImageDataGenerator(rescale=1./255)
# test_datagenerator = ImageDataGenerator(rescale=1./255)

# train_datagenerator = train_datagenerator.flow_from_directory(
#     '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train',
#     target_size=(128,128),
#     batch_size=32,
#     class_mode='binary')

# test_datagenerator = test_datagenerator.flow_from_directory(
#     '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test',
#     target_size=(128,128),
#     batch_size=32,
#     class_mode='binary')

Found 525 images belonging to 3 classes.
Found 91 images belonging to 3 classes.


In [ ]:
#Toei
data_generator = ImageDataGenerator(
    rescale = 1. / 255, 
    shear_range = 0.2, 
    zoom_range = 0.2, 
    horizontal_flip = True,
    vertical_flip = True,
    rotation_range = 180,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    validation_split = 0.2) 

train_generator = data_generator.flow_from_directory(
    '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train', 
    target_size =(128, 128),
    batch_size=32,
    shuffle = True,
    class_mode = 'sparse',
    seed = 42,
    subset='training')

validation_generator = data_generator.flow_from_directory( 
    '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train', 
    target_size =(128, 128),
    batch_size=32,
    shuffle = True,
    class_mode = 'sparse',
    seed = 42,
    subset='validation')


Found 373 images belonging to 3 classes.
Found 93 images belonging to 3 classes.


In [ ]:
# Use the Image Data generator to import the images from the dataset

# X_train = []
# Y_train = []

In [ ]:
#medium
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Medium'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Medium', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(1)

In [ ]:
#ripe
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Ripe'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Ripe', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(2)

In [ ]:
#unripe
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Unripe'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Unripe', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(3)

In [ ]:
#Dome
model = tf.keras.Sequential([

  tf.keras.layers.Conv2D(16, (3,3),padding='same', activation='relu', input_shape=(128,128, 3)),
  tf.keras.layers.MaxPooling2D((2,2),2), 
  
  # tf.keras.layers.Conv2D(32, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  tf.keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D((2,2),2), 

  # tf.keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  # tf.keras.layers.Conv2D(256, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(64, activation='relu'),

  tf.keras.layers.Dense(3, activation='softmax')
])

In [ ]:
model.compile(optimizer = 'adam',
            loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [ ]:
print(model.summary())

Model: "sequential_32"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_94 (Conv2D)           (None, 128, 128, 16)      448       
_________________________________________________________________
max_pooling2d_94 (MaxPooling (None, 64, 64, 16)        0         
_________________________________________________________________
conv2d_95 (Conv2D)           (None, 64, 64, 64)        9280      
_________________________________________________________________
max_pooling2d_95 (MaxPooling (None, 32, 32, 64)        0         
_________________________________________________________________
flatten_32 (Flatten)         (None, 65536)             0         
_________________________________________________________________
dense_88 (Dense)             (None, 64)                4194368   
_________________________________________________________________
dense_89 (Dense)             (None, 3)               

In [ ]:
# X_train = np.array(X_train)
# Y_train = np.array(Y_train)

In [ ]:
model.fit(train_generator, epochs=10, validation_data=validation_generator)

Epoch 1/10
12/12 [==============================] - 15s 1s/step - loss: 1.5809 - accuracy: 0.5013 - val_loss: 0.6848 - val_accuracy: 0.8065
Epoch 2/10
12/12 [==============================] - 14s 1s/step - loss: 0.4464 - accuracy: 0.8740 - val_loss: 0.1986 - val_accuracy: 0.8925
Epoch 3/10
12/12 [==============================] - 14s 1s/step - loss: 0.1526 - accuracy: 0.9491 - val_loss: 0.0611 - val_accuracy: 0.9677
Epoch 4/10
12/12 [==============================] - 14s 1s/step - loss: 0.1539 - accuracy: 0.9437 - val_loss: 0.1841 - val_accuracy: 0.9355
Epoch 5/10
12/12 [==============================] - 14s 1s/step - loss: 0.0938 - accuracy: 0.9571 - val_loss: 0.0395 - val_accuracy: 0.9892
Epoch 6/10
12/12 [==============================] - 14s 1s/step - loss: 0.1278 - accuracy: 0.9625 - val_loss: 0.1409 - val_accuracy: 0.9140
Epoch 7/10
12/12 [==============================] - 14s 1s/step - loss: 0.1610 - accuracy: 0.9276 - val_loss: 0.0322 - val_accuracy: 0.9892
Epoch 8/10
12/12 [==

In [ ]:
# model.fit(X_train,Y_train, epochs=20)

In [ ]:
#Toei
filePath = '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/'

In [ ]:
#Toei
# Save Model
model.save(filePath+'Model/New2papaya.h5')

In [ ]:
model = tf.keras.models.load_model(filePath+'Model/New2papaya.h5')

In [ ]:
# #Dome
# model = tf.keras.models.load_model('DomePapaya.h5')

In [ ]:
# #Dome
# path = '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test/Ripe/ripe_001.PNG'
# img = image.load_img(path, target_size=(128, 128, 3))
# x = image.img_to_array(img)
# x = np.expand_dims(x, axis=0)

# images = np.vstack([x])
# classes = model.predict(images)
# print(classes[0])


In [ ]:
path = filePath+'Predict/papaya_023.PNG'
img = image.load_img(path, target_size=(128, 128, 3))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)

images = np.vstack([x])
classes = model.predict(images)

print(classes[0])

[0. 1. 0.]


In [ ]:
status = np.argmax(classes[0])

def translate(x):
    return {
        0: 'ripe',
        1: 'medium',
        2: 'unripe',
        3: 'error'
    }.get(x, 3)

print(translate(status))
print(classes[0, status])

medium
1.0


In [ ]:
# from keras.models import load_model
# def classify_img(filename):
#   result=[]
#   Loadmodel = load_model('/content/OtherPapaya101.h5')
#   img = cv2.imread(filename)
#   cv2_imshow(img)
  
#   img = cv2.resize(img,(128,128))
#   img = img /255.
#   img = img.reshape(128,128,3)
#   result.append(img)
#   result = np.array(result)

#   final = model.predict(result)
#   np.array(final)
#   if (np.argmax(final)==1):
#     return "It's medium"
#   elif (np.argmax(final)==2):
#     return "It's ripe"
#   else:
#     return "It's unripe"

In [ ]:
# classify_img('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test/Unripe/unripe_013.PNG')

In [ ]:
import cv2
import os

x_predict = []
for filename in os.listdir(filePath+'Predict'):
  f = os.path.join(filePath+'Predict', filename)
  img = image.load_img(f, target_size=(128, 128, 3))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)
  images = np.vstack([x])
  # img = cv2.imread(f)
  # img = image.img_to_array(img)
  # img = cv2.resize(img,(128,128))
  # img = img / 255.
  # img = img.reshape(128,128,3)
  # img = np.expand_dims(img, axis=0)
  classes = model.predict(images)
  x_predict.append(translate(np.argmax(classes[0])))


In [ ]:
x_predict

['medium',
 'medium',
 'ripe',
 'unripe',
 'unripe',
 'unripe',
 'medium',
 'medium',
 'unripe',
 'ripe',
 'unripe',
 'unripe',
 'unripe',
 'unripe',
 'medium',
 'medium',
 'medium',
 'medium',
 'unripe',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'unripe',
 'medium']

In [ ]:
# Confusion matrix
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/PapayaResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[1 7 2]
 [1 6 3]
 [0 5 5]]
              precision    recall  f1-score   support

        ripe       0.50      0.10      0.17        10
      medium       0.33      0.60      0.43        10
      unripe       0.50      0.50      0.50        10

    accuracy                           0.40        30
   macro avg       0.44      0.40      0.37        30
weighted avg       0.44      0.40      0.37        30

