<a href="https://colab.research.google.com/github/earth1429/AI-ClassifyImage/blob/main/Datapapaya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing all necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#
# train_datagenerator = ImageDataGenerator(rescale=1./255)
# test_datagenerator = ImageDataGenerator(rescale=1./255)

# train_datagenerator = train_datagenerator.flow_from_directory(
#     '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train',
#     target_size=(128,128),
#     batch_size=32,
#     class_mode='binary')

# test_datagenerator = test_datagenerator.flow_from_directory(
#     '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test',
#     target_size=(128,128),
#     batch_size=32,
#     class_mode='binary')

Found 1200 images belonging to 3 classes.
Found 300 images belonging to 3 classes.


In [ ]:
#Main
data_generator = ImageDataGenerator(
    rescale = 1. / 255, 
    shear_range = 0.2, 
    zoom_range = 0.2, 
    horizontal_flip = True,
    vertical_flip = True,
    rotation_range = 180,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    validation_split = 0.33) 

train_generator = data_generator.flow_from_directory(
    '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train', 
    target_size =(128, 128),
    batch_size=32,
    shuffle = True,
    class_mode = 'sparse',
    seed = 42,
    subset='training')

validation_generator = data_generator.flow_from_directory( 
    '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train', 
    target_size =(128, 128),
    batch_size=32,
    shuffle = True,
    class_mode = 'sparse',
    seed = 42,
    subset='validation')


Found 804 images belonging to 3 classes.
Found 396 images belonging to 3 classes.


In [ ]:
# Use the Image Data generator to import the images from the dataset

# X_train = []
# Y_train = []

In [ ]:
#medium
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Medium'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Medium', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(1)

In [ ]:
#ripe
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Ripe'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Ripe', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(2)

In [ ]:
#unripe
# for filename in os.listdir('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Unripe'):
#   f = os.path.join('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Train/Unripe', filename)
#   img = cv2.imread(f)
#   img = cv2.resize(img,(128,128))
#   img = img / 255.
#   img = img.reshape(128,128,3)
#   X_train.append(img)
#   Y_train.append(3)

In [ ]:
# Main
model = tf.keras.Sequential([

  tf.keras.layers.Conv2D(16, (3,3),padding='same', activation='relu', input_shape=(128,128, 3)),
  tf.keras.layers.MaxPooling2D((2,2),2), 
  
  # tf.keras.layers.Conv2D(32, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  tf.keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D((2,2),2), 

  # tf.keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  # tf.keras.layers.Conv2D(256, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),

  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024, activation='relu'),
  tf.keras.layers.Dense(3, activation='softmax')
])

In [ ]:
optimizer = keras.optimizers.Adam(lr=1e-3)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model.compile(optimizer = optimizer,
            loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [ ]:
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_13 (Conv2D)          (None, 128, 128, 16)      448       
                                                                 
 max_pooling2d_13 (MaxPoolin  (None, 64, 64, 16)       0         
 g2D)                                                            
                                                                 
 conv2d_14 (Conv2D)          (None, 64, 64, 64)        9280      
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 32, 32, 64)       0         
 g2D)                                                            
                                                                 
 flatten_5 (Flatten)         (None, 65536)             0         
                                                                 
 dense_11 (Dense)            (None, 1024)             

In [ ]:
# X_train = np.array(X_train)
# Y_train = np.array(Y_train)

In [ ]:
 model.fit(train_generator, epochs=15, validation_data=validation_generator)

Epoch 1/15
26/26 [==============================] - 343s 13s/step - loss: 3.8444 - accuracy: 0.5050 - val_loss: 0.6054 - val_accuracy: 0.6566
Epoch 2/15
26/26 [==============================] - 44s 2s/step - loss: 0.5543 - accuracy: 0.7239 - val_loss: 0.4469 - val_accuracy: 0.8106
Epoch 3/15
26/26 [==============================] - 44s 2s/step - loss: 0.3392 - accuracy: 0.8669 - val_loss: 0.2521 - val_accuracy: 0.8864
Epoch 4/15
26/26 [==============================] - 44s 2s/step - loss: 0.2748 - accuracy: 0.8905 - val_loss: 0.1530 - val_accuracy: 0.9419
Epoch 5/15
26/26 [==============================] - 44s 2s/step - loss: 0.2954 - accuracy: 0.8794 - val_loss: 0.2112 - val_accuracy: 0.8939
Epoch 6/15
26/26 [==============================] - 44s 2s/step - loss: 0.3173 - accuracy: 0.8607 - val_loss: 0.1759 - val_accuracy: 0.9192
Epoch 7/15
26/26 [==============================] - 44s 2s/step - loss: 0.2670 - accuracy: 0.8881 - val_loss: 0.1564 - val_accuracy: 0.9419
Epoch 8/15
26/26 [

In [ ]:
# model.fit(X_train,Y_train, epochs=20)

In [ ]:
# Main
filePath = '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/'

In [ ]:
# Main
# Save Model
model.save(filePath+'Model/DomeModelpapaya.h5')

In [ ]:
model = tf.keras.models.load_model(filePath+'Model/DomeModelpapaya.h5')

In [ ]:
#
# model = tf.keras.models.load_model('DomePapaya.h5')

In [ ]:
#
# path = '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test/Ripe/ripe_001.PNG'
# img = image.load_img(path, target_size=(128, 128, 3))
# x = image.img_to_array(img)
# x = np.expand_dims(x, axis=0)

# images = np.vstack([x])
# classes = model.predict(images)
# print(classes[0])


In [ ]:
# Main
def translate(x):
    return {
        0: 'medium',
        1: 'ripe',
        2: 'unripe',
        3: 'error'
    }.get(x, 3)


In [ ]:
# Main
path = '/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test/Ripe/ripe_024.PNG'
img = image.load_img(path, target_size=(128, 128, 3))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
images = np.vstack([x])
classes = model.predict(images)
classes = model.predict(images)
score = tf.nn.softmax(classes[0])
print("Status: ", translate(np.argmax(classes[0])))
print("Confident Level: ", np.max(score)*100)

Status:  ripe
Confident Level:  57.61169195175171


In [ ]:
# from keras.models import load_model
# def classify_img(filename):
#   result=[]
#   Loadmodel = load_model('/content/OtherPapaya101.h5')
#   img = cv2.imread(filename)
#   cv2_imshow(img)
  
#   img = cv2.resize(img,(128,128))
#   img = img /255.
#   img = img.reshape(128,128,3)
#   result.append(img)
#   result = np.array(result)

#   final = model.predict(result)
#   np.array(final)
#   if (np.argmax(final)==1):
#     return "It's medium"
#   elif (np.argmax(final)==2):
#     return "It's ripe"
#   else:
#     return "It's unripe"

In [ ]:
# classify_img('/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Test/Unripe/unripe_013.PNG')

In [ ]:
# Main
import cv2
import os

x_predict = []
# list_of_files = sorted( filter( lambda x: os.path.isfile(os.path.join(filePath+'Predict/Predict02', x)),os.listdir(filePath+'Predict/Predict02') ) )
# for file_name in list_of_files:
#     print(file_name)
    
for filename in sorted(os.listdir(filePath+'Predict/Predict02')):
  f = os.path.join(filePath+'Predict/Predict02', filename)
  print(f)
  img = image.load_img(f, target_size=(128, 128, 3))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)
  images = np.vstack([x])
  # img = cv2.imread(f)
  # img = image.img_to_array(img)
  # img = cv2.resize(img,(128,128))
  # img = img / 255.
  # img = img.reshape(128,128,3)
  # img = np.expand_dims(img, axis=0)
  classes = model.predict(images)
  score = tf.nn.softmax(classes[0])
  # print(np.max(score), translate(np.argmax(classes[0])))
  # print(np.max(score))
  x_predict.append(translate(np.argmax(classes[0])))


/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_01.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_02.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_03.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_04.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_05.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_06.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_07.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_08.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_09.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_10.PNG
/content/drive/MyDrive/ปี 3 เทอม 1/CSC340 AI/DataTraining/Predict/Predict02/Papaya_11.PNG
/content/d

In [ ]:
x_predict

['unripe',
 'unripe',
 'ripe',
 'ripe',
 'unripe',
 'ripe',
 'unripe',
 'ripe',
 'ripe',
 'ripe',
 'ripe',
 'unripe',
 'ripe',
 'unripe',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'medium',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'medium',
 'ripe',
 'unripe',
 'ripe',
 'medium',
 'ripe',
 'ripe',
 'unripe',
 'ripe',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'unripe',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'medium',
 'ripe',
 'unripe',
 'unripe',
 'ripe',
 'ripe',
 'unripe',
 'unripe',
 'ripe',
 'ripe',
 'medium',
 'unripe',
 'ripe',
 'unripe',
 'ripe']

In [ ]:
# Main
# Confusion matrix
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/Result/PapayaResultV2.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['medium', 'ripe', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['medium', 'ripe', 'unripe']))

[[10 10  0]
 [ 0 20  0]
 [ 0  0 20]]
              precision    recall  f1-score   support

      medium       1.00      0.50      0.67        20
        ripe       0.67      1.00      0.80        20
      unripe       1.00      1.00      1.00        20

    accuracy                           0.83        60
   macro avg       0.89      0.83      0.82        60
weighted avg       0.89      0.83      0.82        60

